#pragma once

typedef struct _IGB_ADAPTER IGB_ADAPTER, *PIGB_ADAPTER;
typedef struct _IGB_DEVICE IGB_DEVICE, *PIGB_DEVICE;
typedef struct _IGB_INTERRUPT IGB_INTERRUPT, *PIGB_INTERRUPT;
typedef struct _IGB_QUEUE_INTERRUPT IGB_QUEUE_INTERRUPT, *PIGB_QUEUE_INTERRUPT;